### ISSUE TITLE
 The eth_protocolVersion API call is gone as it made no sense

### ISSUE THREAD

**Issue by mooonly** [splunk/splunk-connect-for-ethereum#121]
# I got this error
warn Ethereum node failed to respond to protocol version request JsonRpcError: the method eth_protocolVersion does not exist/is not available
# https://blog.ethereum.org/2021/03/03/geth-v1-10-0
This method has been deprecated in geth v1.10

**Comment by tmartin14** [comment]
Are you seeing an error or just a warning.  The return for this call was changed a while back to warn rather than error or fail. See the change[ here]( https://github.com/splunk/splunk-connect-for-ethereum/commit/256c4d94c9ce269f63c0eaa7c216613e7accc98d).

**Comment by mooonly** [comment]
thk
