### ISSUE TITLE
ERROR: for ethlogger  Cannot create container for service ethlogger

### ISSUE THREAD

**Issue by shravankumar147** [splunk/splunk-connect-for-ethereum#87]
Hi I got this error on windows 10 docker, 

I am following this example: https://github.com/splunk/splunk-connect-for-ethereum/tree/master/examples/docker-compose-basic
with mainnet and infura_project_id

But unable  to start ethlogger with below error. 

> docker-compose up -d
splunk is up-to-date
Creating ethlogger ... error

ERROR: for ethlogger  Cannot create container for service ethlogger: mkdir C:\path_to_dir\splunk-connect-for-ethereum\examples\docker-compose-basic\abis: The system cannot find the file specified.

ERROR: Encountered errors while bringing up the project.

Any help is greatly appreciated

**Comment by atoulme** [comment]
This is odd. The example mounts a folder relative to the docker-compose.yml file named `./abis`. The folder should be created automatically by Docker.
There can be multiple reasons why Docker is unable to create or resolve this folder.
Please try creating the abis folder yourself or remove the mount point from the example docker-compose.yml file.
I hope this helps.

**Comment by atoulme** [comment]
I hope the workaround above solved your problem. I am now going to close this issue, please reopen if you need further help.
